### ISSUE TITLE
Would you mind if I submitted these samples to the main sharpdx samples repository?

### ISSUE THREAD

**Issue by Axiverse** [hon-ya/SharpDXSamples#29]
I found these samples very helpful, however they were hard to find. I think that many people would benefit if these samples were available in the primary sharpdx samples (https://github.com/sharpdx/SharpDX-Samples) I could translate the comments and submit a pull request with your permission.

Thanks,

**Comment by hon-ya** [comment]
Sorry to delay. I didn't notice.
I added a license file as "The Unlicense". You can use these samples freely.
I hope this will help you.
